template: |
  # Changes In This Version

  $CHANGES

categories:
  - title: 'New Features'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Dependency Updates'
    label: 'dependency update'

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
  - label: 'dependency update'
    branch:
      - '/update\/.+/'
