apiVersion: v1
kind: Service
metadata:
  name: surge
  labels:
    app: surge
spec:
  ports:
  - port: 6667
    name: surge-server
    targetPort: 6667
  - port: 7777
    name: business-app
    targetPort: 7777
  selector:
    app: surge
  type: NodePort   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surge
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: surge
  template:
    metadata:
      labels:
        app: surge
    spec:
      containers:
      - name: surge-server
        image: surge-engine-multilanguage:0.5.24-SNAPSHOT
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "500m"
            memory: "1000Mi"
          limits:
            cpu: "500m"
            memory: "1000Mi"
        ports:
          - containerPort: 6667
            name: surge-server
            protocol: TCP
        env:
          - name: "BUSINESS_LOGIC_HOST"
            value: "localhost"
          - name: "BUSINESS_LOGIC_PORT"
            value: "7777"
          - name: "LOCAL_SERVER_HOST"
            value: "0.0.0.0"
          - name: "LOCAL_SERVER_PORT"
            value: "6667"
          - name: "KAFKA_BROKERS"
            value: "my-cluster-kafka-bootstrap:9092"

      - name: business-app
        image: surge-engine-multilanguage-poc-business-app:0.5.24-SNAPSHOT
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "500m"
            memory: "1000Mi"
          limits:
            cpu: "500m"
            memory: "1000Mi"
        ports:
          - containerPort: 7777
            name: business-app
            protocol: TCP
        env:       
          - name: "SURGE_SERVER_HOST"
            value: "localhost"
          - name: "SURGE_SERVER_PORT"
            value: "6667"
          - name: "LOCAL_SERVER_HOST"
            value: "0.0.0.0"
          - name: "LOCAL_SERVER_PORT"
            value: "7777"
          - name: "KAFKA_BROKERS"
            value: "my-cluster-kafka-bootstrap:9092"