name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.16.0
      - name: lint
        run: 'sbt -jvmArgsAppend "-XX:+UseJVMCINativeLibrary" scalastyle && sbt -jvmArgsAppend "-XX:+UseJVMCINativeLibrary" "scalafmtCheckAll;scalafmtSbtCheck"'
      #- name: check-binary-compatibility
      #  run: 'sbt mimaReportBinaryIssues'
      - name: test
        run: 'sbt clean coverage test coverageReport coverageAggregate'
      - name: publish test report
        uses: mikepenz/action-junit-report@v2
        if: 'always()'
        with:
          report_paths: 'target/test-reports/*.xml'
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: build docs
        run: 'sbt surge-docs/clean surge-docs/makeSite'
